
-- Base PostgreSQL / Supabase para a migração do sistema legado.

create extension if not exists pgcrypto;

create table if not exists config (
  id bigint primary key,
  nome text not null,
  email text,
  telefone_fixo text,
  telefone_whatsapp text,
  endereco text,
  logo text,
  icone text,
  logo_rel text,
  tipo_rel text,
  instagram text,
  tipo_comissao text,
  texto_rodape text,
  img_banner_index text,
  texto_sobre text,
  imagem_sobre text,
  icone_site text,
  mapa text,
  texto_fidelidade text,
  quantidade_cartoes integer,
  texto_agendamento text,
  msg_agendamento text,
  cnpj text,
  cidade text,
  agendamento_dias integer,
  itens_pag integer,
  minutos_aviso integer,
  token text,
  instancia text,
  url_video text,
  posicao_video text,
  taxa_sistema numeric(10,2),
  lanc_comissao text,
  ativo text,
  porc_servico numeric(10,2),
  pgto_api text,
  api text,
  entrada text,
  fundo_login text,
  opcao_pagar text,
  api_pagamento text,
  public_key_mp text,
  access_token_mp text,
  asaas text,
  email_menuia text,
  plano_menuia text,
  validade_menuia text,
  senha_menuia text
);

create table if not exists textos_index (
  id bigint primary key,
  titulo text not null,
  descricao text not null
);

create table if not exists cat_servicos (
  id bigint primary key,
  nome text not null
);

create table if not exists servicos (
  id bigint primary key,
  nome text not null,
  categoria bigint references cat_servicos (id),
  valor numeric(10,2) not null default 0,
  foto text,
  dias_retorno integer,
  ativo text,
  comissao numeric(10,2),
  tempo integer not null default 30
);

create table if not exists usuarios (
  id bigint primary key,
  nome text not null,
  email text,
  cpf text,
  senha text,
  senha_crip text,
  nivel text,
  data date,
  ativo text,
  telefone text,
  endereco text,
  foto text,
  atendimento text,
  tipo_chave text,
  chave_pix text,
  intervalo integer default 15,
  comissao integer,
  visualizar text
);

create table if not exists servicos_func (
  id bigint primary key,
  funcionario bigint not null references usuarios (id),
  servico bigint not null references servicos (id),
  unique(funcionario, servico)
);

create table if not exists dias (
  id bigint primary key,
  dia text not null,
  funcionario bigint not null references usuarios (id),
  inicio time not null,
  final time not null,
  inicio_almoco time,
  final_almoco time
);

create table if not exists dias_bloqueio (
  id bigint primary key,
  data date not null,
  funcionario bigint default 0,
  usuario bigint
);

create table if not exists produtos (
  id bigint primary key,
  nome text not null,
  descricao text,
  categoria bigint,
  valor_compra numeric(10,2),
  valor_venda numeric(10,2) not null default 0,
  estoque integer not null default 0,
  foto text,
  nivel_estoque integer default 0
);

create table if not exists comentarios (
  id bigint primary key,
  nome text not null,
  texto text not null,
  foto text,
  ativo text not null default 'Sim'
);

create table if not exists clientes (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique,
  nome text not null,
  email text,
  telefone text not null unique,
  endereco text,
  data_nasc date,
  data_cad date default current_date,
  cartoes integer default 0,
  data_retorno date,
  ultimo_servico bigint references servicos (id),
  alertado text default 'Não',
  cpf text,
  senha_crip text,
  marketing text,
  usuario bigint references usuarios (id)
);

create table if not exists agendamentos (
  id bigint generated by default as identity primary key,
  funcionario bigint not null references usuarios (id),
  cliente bigint not null references clientes (id),
  data date not null,
  hora time not null,
  obs text,
  data_lanc date default current_date,
  usuario bigint,
  status text not null default 'Agendado',
  servico bigint not null references servicos (id),
  hash text,
  ref_pix text,
  valor_pago numeric(10,2),
  validador bigint default 0,
  phone text,
  created_at timestamptz not null default now(),
  unique(funcionario, data, hora)
);

create table if not exists agendamentos_temp (
  id bigint generated by default as identity primary key,
  funcionario bigint not null references usuarios (id),
  cliente bigint not null references clientes (id),
  data date not null,
  hora time not null,
  obs text,
  data_lanc date default current_date,
  usuario bigint,
  status text not null default 'Agendado',
  servico bigint not null references servicos (id),
  hash text,
  ref_pix text,
  valor_pago numeric(10,2),
  created_at timestamptz not null default now()
);

create table if not exists horarios_agd (
  id bigint generated by default as identity primary key,
  data date not null,
  funcionario bigint not null references usuarios (id),
  horario time not null,
  unique(data, funcionario, horario)
);

create table if not exists grupo_assinaturas (
  id bigint primary key,
  nome text not null,
  ativo text not null
);

create table if not exists itens_assinaturas (
  id bigint primary key,
  grupo bigint not null references grupo_assinaturas (id),
  nome text not null,
  valor numeric(10,2) not null,
  ativo text not null,
  c1 text, c2 text, c3 text, c4 text, c5 text, c6 text,
  c7 text, c8 text, c9 text, c10 text, c11 text, c12 text
);

create table if not exists frequencias (
  id bigint primary key,
  frequencia text not null,
  dias integer not null
);

-- Support tables for modernized contact and access flows
create table if not exists contatos_site (
  id bigint generated by default as identity primary key,
  nome text not null,
  telefone text,
  email text,
  mensagem text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_agendamentos_profissional_data on agendamentos (funcionario, data);
create index if not exists idx_agendamentos_cliente on agendamentos (cliente);
create index if not exists idx_servicos_func_servico on servicos_func (servico);
