-- Portal access, analytics and Mercado Pago payment flow support

create table if not exists user_profiles (
  auth_user_id uuid primary key,
  role text not null check (role in ('cliente', 'funcionario')),
  cliente_id bigint references clientes (id) on delete set null,
  usuario_id bigint references usuarios (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_profiles_role_ref_check check (
    (role = 'cliente' and cliente_id is not null and usuario_id is null)
    or
    (role = 'funcionario' and usuario_id is not null and cliente_id is null)
  )
);

create index if not exists idx_user_profiles_role on user_profiles (role);
create index if not exists idx_user_profiles_cliente on user_profiles (cliente_id);
create index if not exists idx_user_profiles_usuario on user_profiles (usuario_id);

create table if not exists user_login_events (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null,
  role text not null check (role in ('cliente', 'funcionario')),
  logged_at timestamptz not null default now()
);

create index if not exists idx_user_login_events_logged_at on user_login_events (logged_at desc);
create index if not exists idx_user_login_events_role_logged_at on user_login_events (role, logged_at desc);

create table if not exists orders (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid,
  cliente_id bigint references clientes (id) on delete set null,
  amount numeric(10,2) not null,
  currency text not null default 'BRL',
  status text not null default 'pending',
  description text,
  external_reference text not null unique,
  mp_preference_id text unique,
  mp_payment_id bigint unique,
  metadata jsonb not null default '{}'::jsonb,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_orders_status_created_at on orders (status, created_at desc);
create index if not exists idx_orders_cliente on orders (cliente_id);
create index if not exists idx_orders_auth_user_id on orders (auth_user_id);

create table if not exists payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references orders (id) on delete cascade,
  provider text not null default 'mercadopago',
  status text not null,
  amount numeric(10,2),
  currency text not null default 'BRL',
  external_payment_id text not null,
  raw_payload jsonb not null default '{}'::jsonb,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(provider, external_payment_id)
);

create index if not exists idx_payments_order_id on payments (order_id);
create index if not exists idx_payments_status_created_at on payments (status, created_at desc);

create table if not exists payment_webhook_events (
  id uuid primary key default gen_random_uuid(),
  provider text not null,
  external_event_id text not null,
  event_type text,
  payload jsonb not null default '{}'::jsonb,
  processing_status text not null default 'received',
  retry_count integer not null default 0,
  error_message text,
  order_id uuid references orders (id) on delete set null,
  payment_id uuid references payments (id) on delete set null,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  unique(provider, external_event_id)
);

create index if not exists idx_payment_webhook_events_provider_received_at on payment_webhook_events (provider, received_at desc);
create index if not exists idx_payment_webhook_events_processing_status on payment_webhook_events (processing_status, received_at desc);
