-- Normalized panel structure for employees, services, products, schedules and dashboard

create table if not exists service_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

insert into service_categories (name)
values ('cabelo'), ('unhas'), ('estética'), ('sobrancelha'), ('maquiagem')
on conflict (name) do nothing;

create table if not exists employees (
  id bigint generated by default as identity primary key,
  legacy_user_id bigint unique references usuarios (id) on delete set null,
  auth_user_id uuid unique,
  name text not null,
  photo_url text,
  phone text,
  email text not null unique,
  cpf text not null,
  role text not null default 'funcionario',
  is_active boolean not null default true,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint employees_role_check check (role in ('funcionario','administrador'))
);

create unique index if not exists uq_employees_cpf_normalized on employees ((regexp_replace(cpf, '\\D', '', 'g')));
create index if not exists idx_employees_name on employees (name);
create index if not exists idx_employees_active on employees (is_active);

create table if not exists services (
  id bigint generated by default as identity primary key,
  legacy_service_id bigint unique references servicos (id) on delete set null,
  name text not null,
  description text,
  price numeric(10,2) not null default 0,
  duration_minutes integer not null default 30,
  photo_url text,
  category_id bigint references service_categories (id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_services_name on services (name);
create index if not exists idx_services_active on services (is_active);
create index if not exists idx_services_category on services (category_id);

create table if not exists employee_services (
  employee_id bigint not null references employees (id) on delete cascade,
  service_id bigint not null references services (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (employee_id, service_id)
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  legacy_product_id bigint unique references produtos (id) on delete set null,
  name text not null,
  description text,
  price numeric(10,2) not null default 0,
  photo_url text,
  stock integer not null default 0,
  sku text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_products_sku on products (sku) where sku is not null;
create index if not exists idx_products_name on products (name);
create index if not exists idx_products_active on products (is_active);

create table if not exists business_hours (
  id bigint generated by default as identity primary key,
  weekday integer not null,
  start_time time,
  end_time time,
  break_start time,
  break_end time,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint business_hours_weekday_check check (weekday between 0 and 6),
  unique (weekday)
);

create table if not exists employee_work_hours (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees (id) on delete cascade,
  weekday integer not null,
  start_time time,
  end_time time,
  break_start time,
  break_end time,
  is_working_day boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint employee_work_hours_weekday_check check (weekday between 0 and 6),
  unique (employee_id, weekday)
);

create index if not exists idx_employee_work_hours_employee on employee_work_hours (employee_id);

create table if not exists schedule_blocks (
  id bigint generated by default as identity primary key,
  employee_id bigint references employees (id) on delete cascade,
  block_date date not null,
  start_time time,
  end_time time,
  reason text,
  block_type text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint schedule_blocks_block_type_check check (block_type in ('folga','ferias','falta','bloqueio_manual','feriado'))
);

create index if not exists idx_schedule_blocks_date on schedule_blocks (block_date);
create index if not exists idx_schedule_blocks_employee on schedule_blocks (employee_id);

-- Optional compatibility seed from legacy users/services/products
insert into employees (legacy_user_id, name, photo_url, phone, email, cpf, role, is_active, description)
select
  u.id,
  u.nome,
  case when u.foto is null or btrim(u.foto) = '' then null else '/sistema/painel/img/perfil/' || u.foto end,
  u.telefone,
  u.email,
  coalesce(nullif(regexp_replace(u.cpf, '\\D', '', 'g'), ''), lpad(u.id::text, 11, '0')),
  case when lower(coalesce(u.nivel,'')) = 'administrador' then 'administrador' else 'funcionario' end,
  coalesce(u.ativo, 'Sim') = 'Sim',
  null
from usuarios u
where u.email is not null and btrim(u.email) <> ''
on conflict (legacy_user_id) do nothing;

insert into services (legacy_service_id, name, description, price, duration_minutes, photo_url, is_active)
select
  s.id,
  s.nome,
  null,
  coalesce(s.valor,0),
  coalesce(s.tempo,30),
  case when s.foto is null or btrim(s.foto) = '' then null else '/sistema/painel/img/servicos/' || s.foto end,
  coalesce(s.ativo,'Sim') = 'Sim'
from servicos s
on conflict (legacy_service_id) do nothing;

insert into products (legacy_product_id, name, description, price, photo_url, stock, sku, is_active)
select
  p.id,
  p.nome,
  p.descricao,
  coalesce(p.valor_venda,0),
  case when p.foto is null or btrim(p.foto) = '' then null else '/sistema/painel/img/produtos/' || p.foto end,
  coalesce(p.estoque,0),
  null,
  coalesce(p.estoque,0) > 0
from produtos p
on conflict (legacy_product_id) do nothing;

insert into employee_services (employee_id, service_id)
select e.id, s.id
from servicos_func sf
join employees e on e.legacy_user_id = sf.funcionario
join services s on s.legacy_service_id = sf.servico
on conflict do nothing;
