-- System alignment migration (compat mode)
-- Goal:
-- 1) Keep current code working (legacy tables stay as source of truth for now)
-- 2) Prepare/align database for new panel and payment flows
-- 3) Add safety constraints and sync bridges without destructive drops

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- 0) Ensure key modern tables exist (for environments that skipped migrations)
-- ---------------------------------------------------------------------------

create table if not exists user_profiles (
  auth_user_id uuid primary key,
  role text not null check (role in ('cliente', 'funcionario', 'administrador')),
  cliente_id bigint references clientes (id) on delete set null,
  usuario_id bigint references usuarios (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists user_profiles drop constraint if exists user_profiles_role_ref_check;
alter table if exists user_profiles
  add constraint user_profiles_role_ref_check
  check (
    (role = 'cliente' and cliente_id is not null and usuario_id is null)
    or
    (role = 'funcionario' and usuario_id is not null and cliente_id is null)
    or
    (role = 'administrador' and usuario_id is not null and cliente_id is null)
  );

create index if not exists idx_user_profiles_role on user_profiles (role);
create index if not exists idx_user_profiles_cliente on user_profiles (cliente_id);
create index if not exists idx_user_profiles_usuario on user_profiles (usuario_id);

create table if not exists user_login_events (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null,
  role text not null check (role in ('cliente', 'funcionario', 'administrador')),
  logged_at timestamptz not null default now()
);

create index if not exists idx_user_login_events_logged_at on user_login_events (logged_at desc);
create index if not exists idx_user_login_events_role_logged_at on user_login_events (role, logged_at desc);

create table if not exists orders (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid,
  cliente_id bigint references clientes (id) on delete set null,
  amount numeric(10,2) not null,
  currency text not null default 'BRL',
  status text not null default 'pending',
  description text,
  external_reference text not null unique,
  mp_preference_id text unique,
  mp_payment_id bigint unique,
  metadata jsonb not null default '{}'::jsonb,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references orders (id) on delete cascade,
  provider text not null default 'mercadopago',
  status text not null,
  amount numeric(10,2),
  currency text not null default 'BRL',
  external_payment_id text not null,
  raw_payload jsonb not null default '{}'::jsonb,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(provider, external_payment_id)
);

create table if not exists payment_webhook_events (
  id uuid primary key default gen_random_uuid(),
  provider text not null,
  external_event_id text not null,
  event_type text,
  payload jsonb not null default '{}'::jsonb,
  processing_status text not null default 'received',
  retry_count integer not null default 0,
  error_message text,
  order_id uuid references orders (id) on delete set null,
  payment_id uuid references payments (id) on delete set null,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  unique(provider, external_event_id)
);

create index if not exists idx_orders_status_created_at on orders (status, created_at desc);
create index if not exists idx_orders_cliente on orders (cliente_id);
create index if not exists idx_orders_auth_user_id on orders (auth_user_id);
create index if not exists idx_payments_order_id on payments (order_id);
create index if not exists idx_payments_status_created_at on payments (status, created_at desc);
create index if not exists idx_payment_webhook_events_provider_received_at on payment_webhook_events (provider, received_at desc);
create index if not exists idx_payment_webhook_events_processing_status on payment_webhook_events (processing_status, received_at desc);

-- ---------------------------------------------------------------------------
-- 1) Identity consistency (email/cpf mandatory + unique) with safe backfill
-- ---------------------------------------------------------------------------

update usuarios
set email = concat('usuario', id, '@placeholder.local')
where email is null or btrim(email) = '';

update clientes
set email = concat('cliente', id, '@placeholder.local')
where email is null or btrim(email) = '';

update usuarios
set cpf = lpad(id::text, 11, '0')
where cpf is null or regexp_replace(cpf, '\D', '', 'g') = '';

update clientes
set cpf = lpad(id::text, 11, '9')
where cpf is null or regexp_replace(cpf, '\D', '', 'g') = '';

alter table usuarios alter column email set not null;
alter table usuarios alter column cpf set not null;
alter table clientes alter column email set not null;
alter table clientes alter column cpf set not null;

create unique index if not exists uq_usuarios_email_lower on usuarios ((lower(email)));
create unique index if not exists uq_clientes_email_lower on clientes ((lower(email)));
create unique index if not exists uq_usuarios_cpf_normalized on usuarios ((regexp_replace(cpf, '\D', '', 'g')));
create unique index if not exists uq_clientes_cpf_normalized on clientes ((regexp_replace(cpf, '\D', '', 'g')));

-- Global cross-table uniqueness for CPF and email (clientes <-> usuarios)
create or replace function enforce_global_identity_uniqueness()
returns trigger
language plpgsql
as $$
declare
  new_cpf text;
  new_email text;
  conflict_id bigint;
begin
  new_cpf := regexp_replace(coalesce(new.cpf, ''), '\D', '', 'g');
  new_email := lower(coalesce(new.email, ''));

  if length(new_cpf) <> 11 then
    raise exception 'CPF invalido para %: %', tg_table_name, new.cpf;
  end if;

  if new_email = '' then
    raise exception 'Email obrigatorio para %', tg_table_name;
  end if;

  if tg_table_name = 'usuarios' then
    select c.id into conflict_id
    from clientes c
    where regexp_replace(c.cpf, '\D', '', 'g') = new_cpf
       or lower(c.email) = new_email
    limit 1;

    if conflict_id is not null then
      raise exception 'CPF/Email ja cadastrado em clientes (id=%)', conflict_id;
    end if;
  elsif tg_table_name = 'clientes' then
    select u.id into conflict_id
    from usuarios u
    where regexp_replace(u.cpf, '\D', '', 'g') = new_cpf
       or lower(u.email) = new_email
    limit 1;

    if conflict_id is not null then
      raise exception 'CPF/Email ja cadastrado em usuarios (id=%)', conflict_id;
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_usuarios_global_identity on usuarios;
create trigger trg_usuarios_global_identity
before insert or update of cpf, email on usuarios
for each row
execute function enforce_global_identity_uniqueness();

drop trigger if exists trg_clientes_global_identity on clientes;
create trigger trg_clientes_global_identity
before insert or update of cpf, email on clientes
for each row
execute function enforce_global_identity_uniqueness();

-- ---------------------------------------------------------------------------
-- 2) Customer phone uniqueness relaxation (fix auto-provision conflicts)
-- ---------------------------------------------------------------------------

alter table if exists clientes drop constraint if exists clientes_telefone_key;
drop index if exists clientes_telefone_key;
create index if not exists idx_clientes_telefone on clientes (telefone);

-- ---------------------------------------------------------------------------
-- 3) Payments <-> Booking explicit linkage and notification log
-- ---------------------------------------------------------------------------

alter table if exists orders add column if not exists booking_id bigint references agendamentos (id) on delete set null;
alter table if exists orders add column if not exists source text not null default 'checkout_pro';
alter table if exists payments add column if not exists booking_id bigint references agendamentos (id) on delete set null;
alter table if exists payment_webhook_events add column if not exists booking_id bigint references agendamentos (id) on delete set null;

create index if not exists idx_orders_booking on orders (booking_id);
create index if not exists idx_orders_source on orders (source);
create index if not exists idx_payments_booking on payments (booking_id);
create index if not exists idx_webhook_booking on payment_webhook_events (booking_id);

update orders o
set booking_id = (o.metadata ->> 'booking_id')::bigint
where o.booking_id is null
  and (o.metadata ? 'booking_id')
  and (o.metadata ->> 'booking_id') ~ '^[0-9]+$'
  and exists (
    select 1
    from agendamentos a
    where a.id = (o.metadata ->> 'booking_id')::bigint
  );

update payments p
set booking_id = o.booking_id
from orders o
where p.order_id = o.id
  and p.booking_id is null
  and o.booking_id is not null;

update payment_webhook_events w
set booking_id = o.booking_id
from orders o
where w.order_id = o.id
  and w.booking_id is null
  and o.booking_id is not null;

create table if not exists booking_notifications (
  id bigint generated by default as identity primary key,
  agendamento_id bigint not null references agendamentos (id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_booking_notifications_agendamento on booking_notifications (agendamento_id, created_at desc);

create or replace function log_booking_notification()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    insert into booking_notifications (agendamento_id, event_type, payload)
    values (
      new.id,
      'booking_created',
      jsonb_build_object(
        'status', new.status,
        'funcionario', new.funcionario,
        'cliente', new.cliente,
        'data', new.data,
        'hora', new.hora
      )
    );
    return new;
  end if;

  if tg_op = 'UPDATE' and coalesce(old.status, '') <> coalesce(new.status, '') then
    insert into booking_notifications (agendamento_id, event_type, payload)
    values (
      new.id,
      'booking_status_changed',
      jsonb_build_object('old_status', old.status, 'new_status', new.status)
    );
    return new;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_log_booking_notification on agendamentos;
create trigger trg_log_booking_notification
after insert or update of status on agendamentos
for each row
execute function log_booking_notification();

-- ---------------------------------------------------------------------------
-- 4) Normalized panel structure (if missing) + legacy compatibility sync
-- ---------------------------------------------------------------------------

create table if not exists service_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

insert into service_categories (name)
values ('cabelo'), ('unhas'), ('estetica'), ('sobrancelha'), ('maquiagem')
on conflict (name) do nothing;

create table if not exists employees (
  id bigint generated by default as identity primary key,
  legacy_user_id bigint unique references usuarios (id) on delete set null,
  auth_user_id uuid unique,
  name text not null,
  photo_url text,
  phone text,
  email text not null unique,
  cpf text not null,
  role text not null default 'funcionario',
  is_active boolean not null default true,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint employees_role_check check (role in ('funcionario', 'administrador'))
);

create unique index if not exists uq_employees_cpf_normalized on employees ((regexp_replace(cpf, '\D', '', 'g')));
create index if not exists idx_employees_name on employees (name);
create index if not exists idx_employees_active on employees (is_active);

create table if not exists services (
  id bigint generated by default as identity primary key,
  legacy_service_id bigint unique references servicos (id) on delete set null,
  name text not null,
  description text,
  price numeric(10,2) not null default 0,
  duration_minutes integer not null default 30,
  photo_url text,
  category_id bigint references service_categories (id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_services_name on services (name);
create index if not exists idx_services_active on services (is_active);
create index if not exists idx_services_category on services (category_id);

create table if not exists employee_services (
  employee_id bigint not null references employees (id) on delete cascade,
  service_id bigint not null references services (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (employee_id, service_id)
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  legacy_product_id bigint unique references produtos (id) on delete set null,
  name text not null,
  description text,
  price numeric(10,2) not null default 0,
  photo_url text,
  stock integer not null default 0,
  sku text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_products_sku on products (sku) where sku is not null;
create index if not exists idx_products_name on products (name);
create index if not exists idx_products_active on products (is_active);

create table if not exists employee_work_hours (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references employees (id) on delete cascade,
  weekday integer not null,
  start_time time,
  end_time time,
  break_start time,
  break_end time,
  is_working_day boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint employee_work_hours_weekday_check check (weekday between 0 and 6),
  unique (employee_id, weekday)
);

create table if not exists schedule_blocks (
  id bigint generated by default as identity primary key,
  employee_id bigint references employees (id) on delete cascade,
  block_date date not null,
  start_time time,
  end_time time,
  reason text,
  block_type text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint schedule_blocks_block_type_check check (block_type in ('folga', 'ferias', 'falta', 'bloqueio_manual', 'feriado'))
);

create index if not exists idx_employee_work_hours_employee on employee_work_hours (employee_id);
create index if not exists idx_schedule_blocks_date on schedule_blocks (block_date);
create index if not exists idx_schedule_blocks_employee on schedule_blocks (employee_id);

-- Backfill normalized from legacy
insert into employees (legacy_user_id, name, photo_url, phone, email, cpf, role, is_active, description)
select
  u.id,
  u.nome,
  case when u.foto is null or btrim(u.foto) = '' then null else u.foto end,
  u.telefone,
  u.email,
  regexp_replace(u.cpf, '\D', '', 'g'),
  case when lower(coalesce(u.nivel, '')) = 'administrador' then 'administrador' else 'funcionario' end,
  coalesce(u.ativo, 'Sim') = 'Sim',
  null
from usuarios u
on conflict (legacy_user_id) do update
set
  name = excluded.name,
  phone = excluded.phone,
  email = excluded.email,
  cpf = excluded.cpf,
  role = excluded.role,
  is_active = excluded.is_active,
  updated_at = now();

insert into services (legacy_service_id, name, description, price, duration_minutes, photo_url, is_active)
select
  s.id,
  s.nome,
  null,
  coalesce(s.valor, 0),
  coalesce(s.tempo, 30),
  s.foto,
  coalesce(s.ativo, 'Sim') = 'Sim'
from servicos s
on conflict (legacy_service_id) do update
set
  name = excluded.name,
  price = excluded.price,
  duration_minutes = excluded.duration_minutes,
  photo_url = excluded.photo_url,
  is_active = excluded.is_active,
  updated_at = now();

insert into products (legacy_product_id, name, description, price, photo_url, stock, is_active)
select
  p.id,
  p.nome,
  p.descricao,
  coalesce(p.valor_venda, 0),
  p.foto,
  coalesce(p.estoque, 0),
  coalesce(p.estoque, 0) > 0
from produtos p
on conflict (legacy_product_id) do update
set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  photo_url = excluded.photo_url,
  stock = excluded.stock,
  is_active = excluded.is_active,
  updated_at = now();

insert into employee_services (employee_id, service_id)
select e.id, s.id
from servicos_func sf
join employees e on e.legacy_user_id = sf.funcionario
join services s on s.legacy_service_id = sf.servico
on conflict do nothing;

insert into employee_work_hours (employee_id, weekday, start_time, end_time, break_start, break_end, is_working_day)
select
  e.id,
  case
    when lower(d.dia) like 'domingo%' then 0
    when lower(d.dia) like 'segunda%' then 1
    when lower(d.dia) like 'ter%' then 2
    when lower(d.dia) like 'quarta%' then 3
    when lower(d.dia) like 'quinta%' then 4
    when lower(d.dia) like 'sexta%' then 5
    when lower(d.dia) like 'sab%' then 6
    else null
  end as weekday,
  d.inicio,
  d.final,
  d.inicio_almoco,
  d.final_almoco,
  true
from dias d
join employees e on e.legacy_user_id = d.funcionario
where d.dia is not null and btrim(d.dia) <> ''
  and (
    lower(d.dia) like 'domingo%' or
    lower(d.dia) like 'segunda%' or
    lower(d.dia) like 'ter%' or
    lower(d.dia) like 'quarta%' or
    lower(d.dia) like 'quinta%' or
    lower(d.dia) like 'sexta%' or
    lower(d.dia) like 'sab%'
  )
on conflict (employee_id, weekday) do update
set
  start_time = excluded.start_time,
  end_time = excluded.end_time,
  break_start = excluded.break_start,
  break_end = excluded.break_end,
  updated_at = now();

-- Legacy -> normalized sync triggers
create or replace function sync_employee_from_legacy_user()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'DELETE' then
    delete from employees where legacy_user_id = old.id;
    return old;
  end if;

  insert into employees (legacy_user_id, name, photo_url, phone, email, cpf, role, is_active, updated_at)
  values (
    new.id,
    new.nome,
    new.foto,
    new.telefone,
    new.email,
    regexp_replace(new.cpf, '\D', '', 'g'),
    case when lower(coalesce(new.nivel, '')) = 'administrador' then 'administrador' else 'funcionario' end,
    coalesce(new.ativo, 'Sim') = 'Sim',
    now()
  )
  on conflict (legacy_user_id) do update
  set
    name = excluded.name,
    photo_url = excluded.photo_url,
    phone = excluded.phone,
    email = excluded.email,
    cpf = excluded.cpf,
    role = excluded.role,
    is_active = excluded.is_active,
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists trg_sync_employee_from_legacy_user on usuarios;
create trigger trg_sync_employee_from_legacy_user
after insert or update or delete on usuarios
for each row
execute function sync_employee_from_legacy_user();

create or replace function sync_service_from_legacy()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'DELETE' then
    delete from services where legacy_service_id = old.id;
    return old;
  end if;

  insert into services (legacy_service_id, name, price, duration_minutes, photo_url, is_active, updated_at)
  values (
    new.id,
    new.nome,
    coalesce(new.valor, 0),
    coalesce(new.tempo, 30),
    new.foto,
    coalesce(new.ativo, 'Sim') = 'Sim',
    now()
  )
  on conflict (legacy_service_id) do update
  set
    name = excluded.name,
    price = excluded.price,
    duration_minutes = excluded.duration_minutes,
    photo_url = excluded.photo_url,
    is_active = excluded.is_active,
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists trg_sync_service_from_legacy on servicos;
create trigger trg_sync_service_from_legacy
after insert or update or delete on servicos
for each row
execute function sync_service_from_legacy();

create or replace function sync_product_from_legacy()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'DELETE' then
    delete from products where legacy_product_id = old.id;
    return old;
  end if;

  insert into products (legacy_product_id, name, description, price, photo_url, stock, is_active, updated_at)
  values (
    new.id,
    new.nome,
    new.descricao,
    coalesce(new.valor_venda, 0),
    new.foto,
    coalesce(new.estoque, 0),
    coalesce(new.estoque, 0) > 0,
    now()
  )
  on conflict (legacy_product_id) do update
  set
    name = excluded.name,
    description = excluded.description,
    price = excluded.price,
    photo_url = excluded.photo_url,
    stock = excluded.stock,
    is_active = excluded.is_active,
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists trg_sync_product_from_legacy on produtos;
create trigger trg_sync_product_from_legacy
after insert or update or delete on produtos
for each row
execute function sync_product_from_legacy();

create or replace function resync_employee_services_from_legacy(legacy_employee_id bigint)
returns void
language plpgsql
as $$
declare
  v_employee_id bigint;
begin
  select id into v_employee_id
  from employees
  where legacy_user_id = legacy_employee_id
  limit 1;

  if v_employee_id is null then
    return;
  end if;

  delete from employee_services
  where employee_id = v_employee_id;

  insert into employee_services (employee_id, service_id)
  select v_employee_id, s.id
  from servicos_func sf
  join services s on s.legacy_service_id = sf.servico
  where sf.funcionario = legacy_employee_id
  on conflict do nothing;
end;
$$;

create or replace function sync_employee_services_from_legacy()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'DELETE' then
    perform resync_employee_services_from_legacy(old.funcionario);
    return old;
  end if;

  perform resync_employee_services_from_legacy(new.funcionario);
  return new;
end;
$$;

drop trigger if exists trg_sync_employee_services_from_legacy on servicos_func;
create trigger trg_sync_employee_services_from_legacy
after insert or update or delete on servicos_func
for each row
execute function sync_employee_services_from_legacy();

create or replace function resync_employee_work_hours_from_legacy(legacy_employee_id bigint)
returns void
language plpgsql
as $$
declare
  v_employee_id bigint;
begin
  select id into v_employee_id
  from employees
  where legacy_user_id = legacy_employee_id
  limit 1;

  if v_employee_id is null then
    return;
  end if;

  delete from employee_work_hours where employee_id = v_employee_id;

  insert into employee_work_hours (employee_id, weekday, start_time, end_time, break_start, break_end, is_working_day)
  select
    v_employee_id,
    case
      when lower(d.dia) like 'domingo%' then 0
      when lower(d.dia) like 'segunda%' then 1
      when lower(d.dia) like 'ter%' then 2
      when lower(d.dia) like 'quarta%' then 3
      when lower(d.dia) like 'quinta%' then 4
      when lower(d.dia) like 'sexta%' then 5
      when lower(d.dia) like 'sab%' then 6
      else null
    end as weekday,
    d.inicio,
    d.final,
    d.inicio_almoco,
    d.final_almoco,
    true
  from dias d
  where d.funcionario = legacy_employee_id
    and d.dia is not null
    and btrim(d.dia) <> ''
    and (
      lower(d.dia) like 'domingo%' or
      lower(d.dia) like 'segunda%' or
      lower(d.dia) like 'ter%' or
      lower(d.dia) like 'quarta%' or
      lower(d.dia) like 'quinta%' or
      lower(d.dia) like 'sexta%' or
      lower(d.dia) like 'sab%'
    )
  on conflict (employee_id, weekday) do update
  set
    start_time = excluded.start_time,
    end_time = excluded.end_time,
    break_start = excluded.break_start,
    break_end = excluded.break_end,
    updated_at = now();
end;
$$;

create or replace function sync_employee_work_hours_from_legacy()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'DELETE' then
    perform resync_employee_work_hours_from_legacy(old.funcionario);
    return old;
  end if;

  perform resync_employee_work_hours_from_legacy(new.funcionario);
  return new;
end;
$$;

drop trigger if exists trg_sync_employee_work_hours_from_legacy on dias;
create trigger trg_sync_employee_work_hours_from_legacy
after insert or update or delete on dias
for each row
execute function sync_employee_work_hours_from_legacy();

-- ---------------------------------------------------------------------------
-- 5) Performance indexes for current APIs
-- ---------------------------------------------------------------------------

create index if not exists idx_agendamentos_status_data on agendamentos (status, data desc);
create index if not exists idx_agendamentos_funcionario_data_status on agendamentos (funcionario, data desc, status);
create index if not exists idx_agendamentos_cliente_data on agendamentos (cliente, data desc);
create index if not exists idx_servicos_func_funcionario on servicos_func (funcionario);
create index if not exists idx_dias_funcionario on dias (funcionario);
create index if not exists idx_orders_created_at on orders (created_at desc);

-- ---------------------------------------------------------------------------
-- 6) Admin bootstrap now happens via runtime endpoint
-- ---------------------------------------------------------------------------
-- (/api/portal/bootstrap-admin), so no hardcoded admin data is persisted here.
