-- Remove manual ID management for legacy catalog tables.
-- Makes IDs auto-generated and keeps sequence aligned with existing data.

do $$
declare
  servicos_seq text;
  produtos_seq text;
begin
  begin
    alter table servicos alter column id add generated by default as identity;
  exception
    when duplicate_object then null;
  end;

  begin
    alter table produtos alter column id add generated by default as identity;
  exception
    when duplicate_object then null;
  end;

  select pg_get_serial_sequence('servicos', 'id') into servicos_seq;
  if servicos_seq is not null then
    execute format(
      'select setval(%L, (select coalesce(max(id), 0) + 1 from servicos), false)',
      servicos_seq
    );
  end if;

  select pg_get_serial_sequence('produtos', 'id') into produtos_seq;
  if produtos_seq is not null then
    execute format(
      'select setval(%L, (select coalesce(max(id), 0) + 1 from produtos), false)',
      produtos_seq
    );
  end if;
end $$;
