-- Garante funcionamento estável de feriados/férias em dias_bloqueio.
-- Idempotente e segura para rodar em base já populada.

do $$
declare
  blocked_seq text;
begin
  -- 1) Normalizações básicas
  update dias_bloqueio
  set funcionario = 0
  where funcionario is null or funcionario < 0;

  -- 2) Remove duplicidades de (data, funcionario) mantendo o menor id
  delete from dias_bloqueio d
  using dias_bloqueio x
  where d.data = x.data
    and coalesce(d.funcionario, 0) = coalesce(x.funcionario, 0)
    and d.id > x.id;

  -- 3) Garante ID automático
  begin
    alter table dias_bloqueio alter column id add generated by default as identity;
  exception
    when duplicate_object then null;
  end;

  select pg_get_serial_sequence('dias_bloqueio', 'id') into blocked_seq;
  if blocked_seq is not null then
    execute format(
      'select setval(%L, (select coalesce(max(id), 0) + 1 from dias_bloqueio), false)',
      blocked_seq
    );
  end if;
end $$;

-- 4) Constraints e índices para consistência/performance
alter table dias_bloqueio alter column funcionario set default 0;
alter table dias_bloqueio alter column funcionario set not null;

alter table dias_bloqueio drop constraint if exists chk_dias_bloqueio_funcionario_non_negative;
alter table dias_bloqueio
  add constraint chk_dias_bloqueio_funcionario_non_negative
  check (funcionario >= 0);

create unique index if not exists uq_dias_bloqueio_data_funcionario
  on dias_bloqueio (data, funcionario);

create index if not exists idx_dias_bloqueio_data
  on dias_bloqueio (data);

create index if not exists idx_dias_bloqueio_funcionario_data
  on dias_bloqueio (funcionario, data);

