-- Financeiro: tabela dedicada para extrato de pagamentos do negocio.
-- Fluxo de agendamento: cliente sem senha (apenas dados cadastrais no booking).

create table if not exists pagamentos_financeiro (
  id bigint generated by default as identity primary key,
  booking_id bigint references agendamentos (id) on delete set null,
  order_id uuid unique references orders (id) on delete set null,
  payment_id uuid references payments (id) on delete set null,
  cliente_nome text not null,
  cliente_cpf text not null,
  data_reserva date not null,
  servico_nome text not null,
  valor numeric(10,2) not null default 0,
  tipo_pagamento text,
  status_pagamento text not null default 'pending',
  sucesso boolean not null default false,
  whatsapp text,
  whatsapp_enviado boolean not null default false,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_pagamentos_financeiro_data_reserva on pagamentos_financeiro (data_reserva desc);
create index if not exists idx_pagamentos_financeiro_sucesso on pagamentos_financeiro (sucesso, created_at desc);
create index if not exists idx_pagamentos_financeiro_booking on pagamentos_financeiro (booking_id);
