create table if not exists planos (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  nome text not null,
  descricao text,
  itens text[] not null default '{}'::text[],
  inclui text[] not null default '{}'::text[],
  texto_pagamento text,
  validade_texto text,
  preco numeric(10,2) not null default 0,
  ativo text not null default 'Sim',
  ordem integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_planos_ativo_ordem on planos (ativo, ordem, id);

insert into planos (slug, nome, descricao, itens, inclui, texto_pagamento, validade_texto, preco, ativo, ordem)
values
  (
    'combo-mensal',
    'Combo Mensal',
    '2x Acidificacao + revitalizacao, 1x Nutricao, 1x Reconstrucao e 4x Finalizacoes.',
    array[
      '2x Acidificacao + revitalizacao',
      '1x Nutricao',
      '1x Reconstrucao',
      '4x Finalizacoes'
    ]::text[],
    array[
      'Lavagem especial',
      'Finalizacao e secagem'
    ]::text[],
    'Pagamento integral na adesao do combo.',
    'Valido ate o mes de setembro.',
    549.90,
    'Sim',
    1
  ),
  (
    'combo-definicao',
    'Combo Definicao',
    '4x Lavagens + finalizacoes para manter seu cabelo impecavel toda semana.',
    array[
      '4x Lavagens + finalizacoes'
    ]::text[],
    array[
      'Lavagem especial',
      'Finalizacao e secagem'
    ]::text[],
    'Pagamento integral na adesao do combo.',
    'Valido ate o mes de setembro.',
    299.90,
    'Sim',
    2
  )
on conflict (slug) do update
set
  nome = excluded.nome,
  descricao = excluded.descricao,
  itens = excluded.itens,
  inclui = excluded.inclui,
  texto_pagamento = excluded.texto_pagamento,
  validade_texto = excluded.validade_texto,
  preco = excluded.preco,
  ativo = excluded.ativo,
  ordem = excluded.ordem,
  updated_at = now();
